[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Projects"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 30

[[main]]
  name = "FAQ"
  url = "/faq/"
  weight = 40

[[main]]
  name = "Submit A Project"
  url = "/submit-a-project/"
  weight = 50

# toml-docs-start sample-navigation
# [[sample]]
#   name = "Blog"
#   url = "/blog/"
#   weight = 10
# toml-docs-end sample-navigation
