[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  url = "/blog/"
  weight = 10
# toml-docs-end sample-navigation
